### ISSUE TITLE
No `-version` command in the CLI

### ISSUE THREAD

**Issue by zfields** [blues/note-cli#1]
I would like to see a `-version` command in the CLI, so I can be certain I'm up-to-date, and I am able to identify limitations or features associated with the version of the CLI I am using.

**Comment by scottfrazer** [comment]
In case this is helpful, this is how I've injected build-time information into Go in the past.  Let's say that `package main` has a declaration `var GitCommit string`. The build script can be inject a value into that variable at build time like this:

```
export GIT_COMMIT=$(git rev-list -1 HEAD)
go build -ldflags "-X main.GitCommit=$GIT_COMMIT"
```

**Comment by stefanvanburen** [comment]
yeah, I've also used that pattern in the past.

Another option might be pulling the Git tag out of the new [`debug/buildinfo`](https://go.dev/doc/go1.18#debug/buildinfo) package, but that requires someone to be building with go 1.18, I believe. (Not sure what we want to support / are using to build the binaries in the releases).

**Comment by bsatrom** [comment]
GoReleaser actually provides the [main.version ldflag by default](https://goreleaser.com/cookbooks/using-main.version), so this was pretty easy to add. See #4
