### ISSUE TITLE
Trouble Building

### ISSUE THREAD

**Issue by thestumbler** [blues/note-cli#9]
The first build of `notecard` works okay.
Second build of `notehub`, the first `go get` command, fails with:
```
github.com/note-cli/notehub imports
	github.com/blues/note-go/notecard imports
	periph.io/x/periph/conn/i2c: cannot find module providing package periph.io/x/periph/conn/i2c
github.com/note-cli/notehub imports
	github.com/blues/note-go/notecard imports
	periph.io/x/periph/conn/i2c/i2creg: cannot find module providing package periph.io/x/periph/conn/i2c/i2creg
github.com/note-cli/notehub imports
	github.com/blues/note-go/notecard imports
	periph.io/x/periph/host: cannot find module providing package periph.io/x/periph/host
```
Running go1.19.5 on Raspi4 Raspbian OS version 20221214, using Pi carrier.
Looks like some changes with periph.io modules? It's been five years since I've used Go, and I couldn't readily sort it out.

**Comment by bsatrom** [comment]
Hey @thestumbler thanks for the report, I'll take a look today. In the meantime, we have pre-compiled binaries for the latest release [here](https://github.com/blues/note-cli/releases/tag/v1.1.0) if you want to try one of those out.
